config/routes.rb
Rails.application.routes.draw do
  resources :home, only: [:index]
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_locale
  def index
  end
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<main>
  <!-- Carousel / Slider -->
  <div id="my-carousel" class="carousel slide" data-ride="carousel" data-interval="4000">

    <!-- Indicators / Bullets-->
    <ol class="carousel-indicators">
      <li data-target="#my-carousel" data-slide-to="0" class="active"></li>
      <li data-target="#my-carousel" data-slide-to="1"></li>
      <li data-target="#my-carousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%=image_tag(asset_path('index-background.jpg'), alt: "Floresta")%>
        <div class="carousel-caption">
          <%= I18n.t("image_description") %>
        </div>
      </div>
      <div class="item">
        <%=image_tag(asset_path("2.jpg"), alt: "2")%>
        <div class="carousel-caption">
          <%= I18n.t("image_description") %>
        </div>
      </div>
      <div class="item text-center">
        <%=image_tag(asset_path("4.jpg"), alt: "4")%>
        <div class="carousel-caption">
          <%= I18n.t("image_description") %>
        </div>
      </div>
    </div> <!-- Wrapper for slides -->
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Home</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="my-navbar navbar navbar-inverse">
      <div class="container-fluid">

        <!-- Mobile Display Button - Toggle Button -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-menu" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
        </div>

        <!-- Links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right" id="collapse-menu">
          <ul class="nav navbar-nav">
            <li><a class="text-center text-uppercase" href="#">
              <%= I18n.t('menu.home')%>
            </a></li>
            <li><a class="text-center text-uppercase" href="#">
              <%= I18n.t('menu.about') %>
            </a></li>
            <li><a class="text-center text-uppercase" href="#">
              <%= I18n.t('menu.clients') %>
            </a></li>
            <li><a class="text-center text-uppercase" href="#">
              <%= I18n.t('menu.contact') %>
            </a></li>
            <li><a class="text-center text-uppercase" href="#">
              <%= I18n.t('menu.location') %>
            </a></li>
          </ul>
        </div>

      </div>
    </nav>
    <%= yield %>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="<%=asset_path('jquery-3.1.1.min.js')%>"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<%=asset_path('bootstrap.min.js')%>"></script>
  </body>
  <footer>
    <% I18n.available_locales.each do |locale|%>
      <%= link_to(locale, home_index_url(locale: locale)) %> <br>
    <% end %>
  </footer>
</html>